# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161lz1BFXSIH8Ay3ZgvVmaQVfQ90X28Kx
"""

months = ['mar', 'jul', 'dec', 'sep', 'apr', 'nov', 'feb', 'may', 'oct', 'aug', 'jun', 'jan']
calendar_order = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

# Manual sorting
sorted_months = []
for month in calendar_order:
    for m in months:
        if m == month:
            sorted_months.append(m)

print("Sorted months:", sorted_months)


print("="*60)
def identity_matrix(n):
    matrix = []

    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        matrix.append(row)

    return matrix

n = 5
identity = identity_matrix(n)

print("Identity Matrix:")
for row in identity:
    print(row)


