# -*- coding: utf-8 -*-
"""Assignment 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOoV4Ldpepjp1VtkbwlXOL15NFno-76C
"""

# 1
s = "abc_de_f gh_i_jkl mn_o pqr_s"
words = s.split()
matches = []

for word in words:
    if '_' in word:
        parts = word.split('_')
        if all(part.islower() for part in parts):
            matches.append(word)
    elif word.islower():
        matches.append(word)

print(matches)

# 2
print("="*60)
import re

emails = ["abc@gmail.com", "xyz.k@ibm.com", "abc_get@wipro.com"]
pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
valid_emails = [email for email in emails if re.match(pattern, email)]
print(valid_emails)

# 3
print("="*60)
s = "my name is abhinav how are you"
words = s.split()
vowel_count = sum(1 for word in words if word[0].lower() in 'aeiou')
print(vowel_count)

# 4
print("="*60)
s = "my name is abhinav how are you"
words = s.split()
non_aecit_count = sum(1 for word in words if all(char.lower() not in 'aecit' for char in word))
print(non_aecit_count)

# 5
print("="*60)
lst = ['my', 'name', 'is', 'abhinav']
filtered = [x for x in lst if 'e' not in x]
print(filtered)

# 6
print("="*60)
s = """My name
is abhinav
how are
you, fine?
"""
lines = s.splitlines()
filtered_lines = [line for line in lines if not re.search(r'start', line)]
print(filtered_lines)

# 7
print("="*60)
lst = ['hello4world', 'test4', '4test', 'no4here']
filtered = []
for x in lst:
    if '4' in x:
        index = x.index('4')
        if index > 0 and index < len(x) - 1:
            filtered.append(x)
print(filtered)

# 8
print("="*60)
lst = ['denim', 'daily', 'sand', 'lovely', 'denote', 'run']
filtered = []
for x in lst:
    if x.startswith('den') or x.endswith('ly'):
        filtered.append(x)
print(filtered)

# 9
print("="*60)
lst = ['A', 'B', 'C']
items = ['B', 'C']
new_lst = [x if x not in items else 'X' for x in lst]
print(new_lst)

# 10
print("="*60)
s = "0x1A 0xB5 not_hex 2F"
words = s.split()
matches = []
for word in words:
    if (word.startswith('0x') or word.startswith('0X')) and all(c in '0123456789abcdefABCDEF' for c in word[2:]):
        matches.append(word)
print(matches)

# 13
print("="*60)
csv1 = ' comma  ,separated ,values \t\r '
csv2 = 'good bad,nice  ice  , 42 , ,   stall   small'

c1 = [field.strip() for field in csv1.split(',')]
c2 = [field.strip() for field in csv2.split(',')]
print(c1, c2)

